### ISSUE TITLE
support LWT (Last Will and Testament)

### ISSUE THREAD

**Issue by CWempe** [flyte/pi-mqtt-gpio#17]
It would be great if the program would support LWT messages.

see: http://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament

and also this comment: http://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/#comment-44936

**Comment by flyte** [comment]
Sure, that's a good idea. Does it have to be configurable, or will the following suffice:

- Status topic at `<prefix>/status`
- Publish (retained) on start up: `running`
- Publish (retained) when exiting: `stopped`
- Last will in case of unclean disconnection: `dead`

**Comment by flyte** [comment]
I guess it's not a big deal to make it configurable, so I'll do that.

**Comment by flyte** [comment]
@CWempe I've added this functionality, so please test with version `0.1.0`. Cheers!

PS. Check the bottom of the readme for config values.

**Comment by vontrapp** [comment]
Can LWT be used to set many topics on death? It would be great if I could use that to clear any retained inputs when it is disconnected.

Or maybe there's another mqtt feature that does the same?

**Comment by flyte** [comment]
@vontrapp I don't think so. This is a good article on the subject:
https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament

If you want to clear retained messages when it's disconnected, would just setting retain = false work?
