### ISSUE TITLE
Why can i not use topic_prefix: /device/pi ?

### ISSUE THREAD

**Issue by dr-apple** [flyte/pi-mqtt-gpio#3]
Why can i not use topic_prefix: /device/pi ?

The / in the  topic_prefix: /device/pi  dosen't work... it every device/pi :-(

**Comment by flyte** [comment]
Because of this line: https://github.com/flyte/pi-mqtt-gpio/blob/develop/pi_mqtt_gpio/server.py#L56

I wasn't aware that topics with a leading slash were valid. If that is the case, then I'll change the .strip() to an .rstrip()

**Comment by flyte** [comment]
That ought to have done the trick. Please don't hesitate to update this ticket if it hasn't.

**Comment by dr-apple** [comment]
Thank you very much !
